apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: iti-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: mostafamahmoud0/test-java-app:v25
        ports:
        - containerPort: 8080
