apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: iti-test
spec:
  type: NodePort        
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080    
